
//0x
{"RLC B", 2, &CPU::RLC_B},
{"RLC C", 2, &CPU::RLC_C},
{"RLC D", 2, &CPU::RLC_D},
{"RLC E", 2, &CPU::RLC_E},
{"RLC H", 2, &CPU::RLC_H},
{"RLC L", 2, &CPU::RLC_L},
{"RLC (HL)", 4, &CPU::RLC_HLp},
{"RLC A", 2, &CPU::RLC_A},
{"RRC B", 2, &CPU::RRC_B},
{"RRC C", 2, &CPU::RRC_C},
{"RRC D", 2, &CPU::RRC_D},
{"RRC E", 2, &CPU::RRC_E},
{"RRC H", 2, &CPU::RRC_H},
{"RRC L", 2, &CPU::RRC_L},
{"RRC HLp", 4, &CPU::RRC_HLp},
{"RRC A", 2, &CPU::RRC_A},

//1x
{"RL B", 2, &CPU::RL_B},
{"RL C", 2, &CPU::RL_C},
{"RL D", 2, &CPU::RL_D},
{"RL E", 2, &CPU::RL_E},
{"RL H", 2, &CPU::RL_H},
{"RL L", 2, &CPU::RL_L},
{"RL (HL)", 4, &CPU::RL_HLp},
{"RL A", 2, &CPU::RL_A},
{"RR B", 2, &CPU::RR_B},
{"RR C", 2, &CPU::RR_C},
{"RR D", 2, &CPU::RR_D},
{"RR E", 2, &CPU::RR_E},
{"RR H", 2, &CPU::RR_H},
{"RR L", 2, &CPU::RR_L},
{"RR (HL)", 4, &CPU::RR_HLp},
{"RR A", 2, &CPU::RR_A},

//2x
{"SLA B", 2, &CPU::SLA_B},
{"SLA C", 2, &CPU::SLA_C},
{"SLA D", 2, &CPU::SLA_D},
{"SLA E", 2, &CPU::SLA_E},
{"SLA H", 2, &CPU::SLA_H},
{"SLA L", 2, &CPU::SLA_L},
{"SLA (HL)", 4, &CPU::SLA_HLp},
{"SLA A", 2, &CPU::SLA_A},
{"SRA B", 2, &CPU::SRA_B},
{"SRA C", 2, &CPU::SRA_C},
{"SRA D", 2, &CPU::SRA_D},
{"SRA E", 2, &CPU::SRA_E},
{"SRA H", 2, &CPU::SRA_H},
{"SRA L", 2, &CPU::SRA_L},
{"SRA (HL)", 4, &CPU::SRA_HLp},
{"SRA A", 2, &CPU::SRA_A},

//3x
{"SWAP B", 2, &CPU::SWAP_B},
{"SWAP C", 2, &CPU::SWAP_C},
{"SWAP D", 2, &CPU::SWAP_D},
{"SWAP E", 2, &CPU::SWAP_E},
{"SWAP H", 2, &CPU::SWAP_H},
{"SWAP L", 2, &CPU::SWAP_L},
{"SWAP (HL)", 4, &CPU::SWAP_HLp},
{"SWAP A", 2, &CPU::SWAP_A},
{"SRL B", 2, &CPU::SRL_B},
{"SRL C", 2, &CPU::SRL_C},
{"SRL D", 2, &CPU::SRL_D},
{"SRL E", 2, &CPU::SRL_E},
{"SRL H", 2, &CPU::SRL_H},
{"SRL L", 2, &CPU::SRL_L},
{"SRL (HL)", 4, &CPU::SRL_HLp},
{"SRL A", 2, &CPU::SRL_A},

//4x
{"BIT 0,B", 2, &CPU::BIT_0_B},
{"BIT 0,C", 2, &CPU::BIT_0_C},
{"BIT 0,D", 2, &CPU::BIT_0_D},
{"BIT 0,E", 2, &CPU::BIT_0_E},
{"BIT 0,H", 2, &CPU::BIT_0_H},
{"BIT 0,L", 2, &CPU::BIT_0_L},
{"BIT 0,(HL)", 3, &CPU::BIT_0_HLp},
{"BIT 0,A", 2, &CPU::BIT_0_A},
{"BIT 1,B", 2, &CPU::BIT_1_B},
{"BIT 1,C", 2, &CPU::BIT_1_C},
{"BIT 1,D", 2, &CPU::BIT_1_D},
{"BIT 1,E", 2, &CPU::BIT_1_E},
{"BIT 1,H", 2, &CPU::BIT_1_H},
{"BIT 1,L", 2, &CPU::BIT_1_L},
{"BIT 1,(HL)", 3, &CPU::BIT_1_HLp},
{"BIT 1,A", 2, &CPU::BIT_1_A},

//5x
{"BIT 2,B", 2, &CPU::BIT_2_B},
{"BIT 2,C", 2, &CPU::BIT_2_C},
{"BIT 2,D", 2, &CPU::BIT_2_D},
{"BIT 2,E", 2, &CPU::BIT_2_E},
{"BIT 2,H", 2, &CPU::BIT_2_H},
{"BIT 2,L", 2, &CPU::BIT_2_L},
{"BIT 2,(HL)", 3, &CPU::BIT_2_HLp},
{"BIT 2,A", 2, &CPU::BIT_2_A},
{"BIT 3,B", 2, &CPU::BIT_3_B},
{"BIT 3,C", 2, &CPU::BIT_3_C},
{"BIT 3,D", 2, &CPU::BIT_3_D},
{"BIT 3,E", 2, &CPU::BIT_3_E},
{"BIT 3,H", 2, &CPU::BIT_3_H},
{"BIT 3,L", 2, &CPU::BIT_3_L},
{"BIT 3,(HL)", 3, &CPU::BIT_3_HLp},
{"BIT 3,A", 2, &CPU::BIT_3_A},

//6x
{"BIT 4,B", 2, &CPU::BIT_4_B},
{"BIT 4,C", 2, &CPU::BIT_4_C},
{"BIT 4,D", 2, &CPU::BIT_4_D},
{"BIT 4,E", 2, &CPU::BIT_4_E},
{"BIT 4,H", 2, &CPU::BIT_4_H},
{"BIT 4,L", 2, &CPU::BIT_4_L},
{"BIT 4,(HL)", 3, &CPU::BIT_4_HLp},
{"BIT 4,A", 2, &CPU::BIT_4_A},
{"BIT 5,B", 2, &CPU::BIT_5_B},
{"BIT 5,C", 2, &CPU::BIT_5_C},
{"BIT 5,D", 2, &CPU::BIT_5_D},
{"BIT 5,E", 2, &CPU::BIT_5_E},
{"BIT 5,H", 2, &CPU::BIT_5_H},
{"BIT 5,L", 2, &CPU::BIT_5_L},
{"BIT 5,(HL)", 3, &CPU::BIT_5_HLp},
{"BIT 5,A", 2, &CPU::BIT_5_A},

//7x
{"BIT 6,B", 2, &CPU::BIT_6_B},
{"BIT 6,C", 2, &CPU::BIT_6_C},
{"BIT 6,D", 2, &CPU::BIT_6_D},
{"BIT 6,E", 2, &CPU::BIT_6_E},
{"BIT 6,H", 2, &CPU::BIT_6_H},
{"BIT 6,L", 2, &CPU::BIT_6_L},
{"BIT 6,(HL)", 3, &CPU::BIT_6_HLp},
{"BIT 6,A", 2, &CPU::BIT_6_A},
{"BIT 7,B", 2, &CPU::BIT_7_B},
{"BIT 7,C", 2, &CPU::BIT_7_C},
{"BIT 7,D", 2, &CPU::BIT_7_D},
{"BIT 7,E", 2, &CPU::BIT_7_E},
{"BIT 7,H", 2, &CPU::BIT_7_H},
{"BIT 7,L", 2, &CPU::BIT_7_L},
{"BIT 7,(HL)", 3, &CPU::BIT_7_HLp},
{"BIT 7,A", 2, &CPU::BIT_7_A},

//8x
{"RES 0,B", 2, &CPU::RES_0_B},
{"RES 0,C", 2, &CPU::RES_0_C},
{"RES 0,D", 2, &CPU::RES_0_D},
{"RES 0,E", 2, &CPU::RES_0_E},
{"RES 0,H", 2, &CPU::RES_0_H},
{"RES 0,L", 2, &CPU::RES_0_L},
{"RES 0,(HL)", 4, &CPU::RES_0_HLp},
{"RES 0,A", 2, &CPU::RES_0_A},
{"RES 1,C", 2, &CPU::RES_1_B},
{"RES 1,D", 2, &CPU::RES_1_C},
{"RES 1,E", 2, &CPU::RES_1_D},
{"RES 1,B", 2, &CPU::RES_1_E},
{"RES 1,H", 2, &CPU::RES_1_H},
{"RES 1,L", 2, &CPU::RES_1_L},
{"RES 1,(HL)", 4, &CPU::RES_1_HLp},
{"RES 1,A", 2, &CPU::RES_1_A},

//9x
{"RES 2,B", 2, &CPU::RES_2_B},
{"RES 2,C", 2, &CPU::RES_2_C},
{"RES 2,D", 2, &CPU::RES_2_D},
{"RES 2,E", 2, &CPU::RES_2_E},
{"RES 2,H", 2, &CPU::RES_2_H},
{"RES 2,L", 2, &CPU::RES_2_L},
{"RES 2,(HL)", 4, &CPU::RES_2_HLp},
{"RES 2,A", 2, &CPU::RES_2_A},
{"RES 3,C", 2, &CPU::RES_3_B},
{"RES 3,D", 2, &CPU::RES_3_C},
{"RES 3,E", 2, &CPU::RES_3_D},
{"RES 3,B", 2, &CPU::RES_3_E},
{"RES 3,H", 2, &CPU::RES_3_H},
{"RES 3,L", 2, &CPU::RES_3_L},
{"RES 3,(HL)", 4, &CPU::RES_3_HLp},
{"RES 3,A", 2, &CPU::RES_3_A},

//Ax
{"RES 4,B", 2, &CPU::RES_4_B},
{"RES 4,C", 2, &CPU::RES_4_C},
{"RES 4,D", 2, &CPU::RES_4_D},
{"RES 4,E", 2, &CPU::RES_4_E},
{"RES 4,H", 2, &CPU::RES_4_H},
{"RES 4,L", 2, &CPU::RES_4_L},
{"RES 4,(HL)", 4, &CPU::RES_4_HLp},
{"RES 4,A", 2, &CPU::RES_4_A},
{"RES 5,C", 2, &CPU::RES_5_B},
{"RES 5,D", 2, &CPU::RES_5_C},
{"RES 5,E", 2, &CPU::RES_5_D},
{"RES 5,B", 2, &CPU::RES_5_E},
{"RES 5,H", 2, &CPU::RES_5_H},
{"RES 5,L", 2, &CPU::RES_5_L},
{"RES 5,(HL)", 4, &CPU::RES_5_HLp},
{"RES 5,A", 2, &CPU::RES_5_A},

//Bx
{"RES 6,B", 2, &CPU::RES_6_B},
{"RES 6,C", 2, &CPU::RES_6_C},
{"RES 6,D", 2, &CPU::RES_6_D},
{"RES 6,E", 2, &CPU::RES_6_E},
{"RES 6,H", 2, &CPU::RES_6_H},
{"RES 6,L", 2, &CPU::RES_6_L},
{"RES 6,(HL)", 4, &CPU::RES_6_HLp},
{"RES 6,A", 2, &CPU::RES_6_A},
{"RES 7,C", 2, &CPU::RES_7_B},
{"RES 7,D", 2, &CPU::RES_7_C},
{"RES 7,E", 2, &CPU::RES_7_D},
{"RES 7,B", 2, &CPU::RES_7_E},
{"RES 7,H", 2, &CPU::RES_7_H},
{"RES 7,L", 2, &CPU::RES_7_L},
{"RES 7,(HL)", 4, &CPU::RES_7_HLp},
{"RES 7,A", 2, &CPU::RES_7_A},

//Cx
{"SET 0,B", 2, &CPU::SET_0_B},
{"SET 0,C", 2, &CPU::SET_0_C},
{"SET 0,D", 2, &CPU::SET_0_D},
{"SET 0,E", 2, &CPU::SET_0_E},
{"SET 0,H", 2, &CPU::SET_0_H},
{"SET 0,L", 2, &CPU::SET_0_L},
{"SET 0,(HL)", 4, &CPU::SET_0_HLp},
{"SET 0,A", 2, &CPU::SET_0_A},
{"SET 1,B", 2, &CPU::SET_1_B},
{"SET 1,C", 2, &CPU::SET_1_C},
{"SET 1,D", 2, &CPU::SET_1_D},
{"SET 1,E", 2, &CPU::SET_1_E},
{"SET 1,H", 2, &CPU::SET_1_H},
{"SET 1,L", 2, &CPU::SET_1_L},
{"SET 1,(HL)", 4, &CPU::SET_1_HLp},
{"SET 1,A", 2, &CPU::SET_1_A},

//Dx
{"SET 2,B", 2, &CPU::SET_2_B},
{"SET 2,C", 2, &CPU::SET_2_C},
{"SET 2,D", 2, &CPU::SET_2_D},
{"SET 2,E", 2, &CPU::SET_2_E},
{"SET 2,H", 2, &CPU::SET_2_H},
{"SET 2,L", 2, &CPU::SET_2_L},
{"SET 2,(HL)", 4, &CPU::SET_2_HLp},
{"SET 2,A", 2, &CPU::SET_2_A},
{"SET 3,C", 2, &CPU::SET_3_B},
{"SET 3,D", 2, &CPU::SET_3_C},
{"SET 3,E", 2, &CPU::SET_3_D},
{"SET 3,B", 2, &CPU::SET_3_E},
{"SET 3,H", 2, &CPU::SET_3_H},
{"SET 3,L", 2, &CPU::SET_3_L},
{"SET 3,(HL)", 4, &CPU::SET_3_HLp},
{"SET 3,A", 2, &CPU::SET_3_A},

//Ex
{"SET 4,B", 2, &CPU::SET_4_B},
{"SET 4,C", 2, &CPU::SET_4_C},
{"SET 4,D", 2, &CPU::SET_4_D},
{"SET 4,E", 2, &CPU::SET_4_E},
{"SET 4,H", 2, &CPU::SET_4_H},
{"SET 4,L", 2, &CPU::SET_4_L},
{"SET 4,(HL)", 4, &CPU::SET_4_HLp},
{"SET 4,A", 2, &CPU::SET_4_A},
{"SET 5,C", 2, &CPU::SET_5_B},
{"SET 5,D", 2, &CPU::SET_5_C},
{"SET 5,E", 2, &CPU::SET_5_D},
{"SET 5,B", 2, &CPU::SET_5_E},
{"SET 5,H", 2, &CPU::SET_5_H},
{"SET 5,L", 2, &CPU::SET_5_L},
{"SET 5,(HL)", 4, &CPU::SET_5_HLp},
{"SET 5,A", 2, &CPU::SET_5_A},

//Fx
{"SET 6,B", 2, &CPU::SET_6_B},
{"SET 6,C", 2, &CPU::SET_6_C},
{"SET 6,D", 2, &CPU::SET_6_D},
{"SET 6,E", 2, &CPU::SET_6_E},
{"SET 6,H", 2, &CPU::SET_6_H},
{"SET 6,L", 2, &CPU::SET_6_L},
{"SET 6,(HL)", 4, &CPU::SET_6_HLp},
{"SET 6,A", 2, &CPU::SET_6_A},
{"SET 7,C", 2, &CPU::SET_7_B},
{"SET 7,D", 2, &CPU::SET_7_C},
{"SET 7,E", 2, &CPU::SET_7_D},
{"SET 7,B", 2, &CPU::SET_7_E},
{"SET 7,H", 2, &CPU::SET_7_H},
{"SET 7,L", 2, &CPU::SET_7_L},
{"SET 7,(HL)", 4, &CPU::SET_7_HLp},
{"SET 7,A", 2, &CPU::SET_7_A}
